version: '3.7'
services:

  bot:
    build: .
#    command: sh -c "make migrate && python -m bot"
    command: sh -c "python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A bot.tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A bot.tasks beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app


  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata_tg:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"


volumes:
  pgdata_tg: